name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: RXWatcher/continuum-plugin-repository/.github/workflows/build-plugin.yml@main
    secrets:
      CATALOG_SSH_KEY: ${{ secrets.CATALOG_SSH_KEY }}
    with:
      plugin_name: continuum-plugin-whmcs-login
